version: "3.6"
services:
  redis:
    image: "redis"   
    #ports: 
    #  - "6379:6379"
#    command: redis-server --appendonly yes --stop-writes-on-bgsave-error no --maxmemory 1073741824 --maxmemory-policy  volatile-ttl --maxmemory-samples 5 --slowlog-log-slower-than 10000 --databases 16
    container_name: "redis"
    volumes: 
      - ./data:/data
    networks:
      - back
    
  chitu:
    image: "10.7.0.117:9095/mabo_group/base_application/doctopus_chitu:latest"
    container_name: "chitu"
    # restart: always
    working_dir: /usr/mabo/chitu
    command: python manage.py -t chitu
    depends_on: 
      - redis
    volumes:
      - ./chitu:/usr/mabo/chitu
    networks:
      - back

  ziyan:
    image: "10.7.0.117:9095/mabo_group/base_application/doctopus_ziyan:latest"
    container_name: "ziyan"
    # restart: always
    working_dir: /usr/mabo/ziyan
    command: python  manage.py -t ziyan
    depends_on: 
      - redis
    volumes:
      - ./ziyan:/usr/mabo/ziyan
    networks:
      - back
  
  influxdb:
    image: "influxdb"
    container_name: "influxdb"
    volumes:
      - ./influxdb:/var/lib/influxdb
    networks:
      - back

  chronograf:
    image: "chronograf"
    container_name: "chronograf"
    volumes:
      - ./chronograf:/var/lib/chronograf
    ports:
      - 8888:8888
    networks:
      - back
  
  grafana:
    image: "grafana/grafana"
    container_name: "grafana"
    ports:
      - 3000:3000
    networks:
      - back

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor_docker
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - -enable_load_reader=true
      - -port=8080
    
    networks: 
      - back
  

networks:
  back:
